set -s set-clipboard on
set -as terminal-features ',xterm-256color:clipboard'

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g mouse on
set -g status-style "bg=#191919,fg=#7a7a7a"
set-window-option -g window-status-current-style "fg=#1bfd9c"
