unsetopt BEEP

# Platform specific
case "$(uname -s)" in
  Linux)
    # Load env variable exports
    [[ -f $ZDOTDIR/.dircolors ]]
      eval "$(dircolors $ZDOTDIR/.dircolors)"
  	;;

  Darwin)
    if command -v /opt/homebrew/bin/brew &> /dev/null; then
      eval $(/opt/homebrew/bin/brew shellenv)
    fi
	  ;;
esac

# Load env variable exports
[[ -f $ZDOTDIR/exports.zsh ]] && source $ZDOTDIR/exports.zsh 

# Load aliases
[[ -f $ZDOTDIR/aliases.zsh ]] && source $ZDOTDIR/aliases.zsh

# Load custom functions
[[ -f $ZDOTDIR/helpers.zsh ]] && source $ZDOTDIR/helpers.zsh

# Load local config if present
[[ -f $ZDOTDIR/.zlocal ]] && source $ZDOTDIR/.zlocal

# Create directory for local installed tools
mkdir -p $HOME/.local/bin

# Configure the zsh prompt
setopt prompt_subst
PROMPT='%F{magenta}%m%f$(git_current_branch)'
PROMPT+=' %F{yellow}->%f '

# Fix keycodes
bindkey -v
bindkey "^[[H"  beginning-of-line
bindkey "^[[F"  end-of-line
bindkey "^[[3~" delete-char
bindkey "^R"    history-incremental-search-backward

# Configure persistent history
HISTFILE=$ZDOTDIR/.zhistory
HISTSIZE=4096
HISTFILESIZE=4096
SAVEHIST=4096
setopt EXTENDED_HISTORY
setopt HIST_REDUCE_BLANKS
setopt SHARE_HISTORY

# ZSH plugins to use, will be autoloaded below
plugins=(
  zsh-users/zsh-autosuggestions
  zsh-users/zsh-syntax-highlighting
  jeffreytse/zsh-vi-mode
)

# ZSH plugin configurations
function zvm_config() {
  ZVM_VI_INSERT_ESCAPE_BINDKEY=jk
  ZVM_VI_HIGHLIGHT_FOREGROUND=black
  ZVM_VI_HIGHLIGHT_BACKGROUND=white
  ZVM_INIT_MODE=sourcing
}

# Set auto suggest completion to ctrl-space
bindkey '^ ' autosuggest-accept

# Load the plugins
plugin-load $plugins

# Disable underlines of zsh paths in command input
(( ${+ZSH_HIGHLIGHT_STYLES} )) || typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[path]=none
ZSH_HIGHLIGHT_STYLES[path_prefix]=none

# Source FZF and install for ZSH
fzf_path="$HOME/.local/share/fzf"
if [[ ! -d $fzf_path ]]; then
  echo "Cloning FZF..."
  git clone --quiet --depth 1 https://github.com/junegunn/fzf.git $fzf_path
  $fzf_path/install --key-bindings --completion --no-update-rc --no-bash --no-zsh
  ln -s $fzf_path/bin/fzf $HOME/.local/bin/fzf
  source $fzf_path/shell/completion.zsh
  source $fzf_path/shell/key-bindings.zsh
else
  source $fzf_path/shell/completion.zsh
  source $fzf_path/shell/key-bindings.zsh
fi

# Configure FZF
if [[ -d $fzf_path ]]; then
  export FZF_DEFAULT_OPTS="--height 20% --layout reverse --border top"
  export FZF_CTRL_R_OPTS="
  --bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort'
  --color header:italic
  --header 'Press CTRL-Y to copy command into clipboard'"
fi

# Source and use Starship prompt if available
starship_path="$HOME/.local/share/starship"
if [[ ! -d $starship_path ]]; then
  echo "Cloning Starship..."
  mkdir -p $starship_path
  curl -sS https://starship.rs/install.sh | sh -s -- -b $starship_path -y
  ln -s $starship_path/starship $HOME/.local/bin/starship
else
  if command -v starship &> /dev/null; then
    eval "$(starship init zsh)"
  fi
fi


. "$HOME/.local/share/../bin/env"
